/** Bump when Terms or Privacy change materially — prompts re-acceptance in the app. */
export const LEGAL_VERSION = "2026-05-23";

export const LEGAL_LAST_UPDATED = "May 23, 2026";

/**
 * Fill in before commercial launch / attorney review.
 * Use a registered-agent or PO Box address — not a personal residence.
 */
/** Legal entity operating MIMS — update when your LLC is filed (e.g. Petty Apartment LLC). */
export const COMPANY_NAME = "Petty Apartment LLC";
export const COMPANY_MAILING_ADDRESS =
  "[Registered agent or PO Box — City, State ZIP — update before launch]";

export const LEGAL_OPERATOR_NAME = COMPANY_NAME;
export const LEGAL_CONTACT_EMAIL = "support@mims.app";

export const APP_TAGLINE =
  "Educational pricing and deal-prep estimates for independent freelancers.";

export const LOADING_STEPS = [
  "Pulling freelance market rate estimates…",
  "Factoring in client footprint signals…",
  "Estimating budget capacity…",
  "Scoring close-likelihood…",
  "Preparing your deal guidance…",
] as const;

export const APP_DISCLAIMER =
  "MIMS provides educational pricing and deal-prep estimates based on the information you enter. Results are not legal, financial, tax, accounting, or contract advice, and are not a guarantee of what any client will accept. MIMS is for independent freelance professionals only. Review your own agreements, confirm freelance market fit, and use your judgment before sending any quote, invoice, or scope.";

export const DOC_EXPORT_DISCLAIMER =
  "DRAFT — NOT LEGAL ADVICE. This document was generated by MIMS as a starting template from your inputs. It is not a lawyer-drafted agreement. Have a qualified attorney review and customize all terms (including usage, payment, kill fees, and cancellation) before sending to a client or signing.";

/** Shown on Deal Guidance (Blueprint + Sim). Original MIMS coaching — adapt before sending. */
export const NEGOTIATION_COACHING_DISCLAIMER =
  "Original MIMS educational coaching only — not legal, financial, or contract advice. Adapt all draft language before you send it. Have a qualified attorney review business terms, usage rights, and agreements when stakes are high.";

/**
 * Render immediately above any Subscribe / checkout button (California Auto-Rewewal Law).
 * Replace [PLAN PRICE] and [BILLING PERIOD] when you wire billing UI.
 */
export function autoRenewalDisclosure(planPrice: string, billingPeriod = "month"): string {
  return (
    `By subscribing, you authorize ${COMPANY_NAME} to charge your payment method ${planPrice} plus applicable taxes at checkout and at each renewal until you cancel. ` +
    `Your subscription renews automatically every ${billingPeriod} unless you cancel before the renewal date. ` +
    `Cancel anytime via account settings or by emailing ${LEGAL_CONTACT_EMAIL}; cancellation takes effect at the end of the current paid period. ` +
    `Where required by law (including California), we will send renewal reminders before automatic charges.`
  );
}

/** Default copy when plan price is not yet wired — prefer autoRenewalDisclosure("$10 per month") at checkout. */
export const AUTO_RENEWAL_DISCLOSURE_PLACEHOLDER = autoRenewalDisclosure(
  "$10 per month",
  "month",
);

export const CONSENT_STORAGE_KEY = "mimsLegalConsent";

export type LegalConsentRecord = {
  termsVersion: string;
  privacyVersion: string;
  acceptedAt: string;
};

export function recordLegalConsent(): void {
  if (typeof window === "undefined") return;
  const record: LegalConsentRecord = {
    termsVersion: LEGAL_VERSION,
    privacyVersion: LEGAL_VERSION,
    acceptedAt: new Date().toISOString(),
  };
  localStorage.setItem(CONSENT_STORAGE_KEY, JSON.stringify(record));
}

export function readLegalConsent(): LegalConsentRecord | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(CONSENT_STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as LegalConsentRecord;
  } catch {
    return null;
  }
}

/** True only on first visit — before user has ever accepted (blocking modal). */
export function needsFirstLaunchConsent(): boolean {
  return readLegalConsent() === null;
}

/** True if user must accept (or re-accept) current Terms & Privacy. */
export function needsLegalReacceptance(): boolean {
  const record = readLegalConsent();
  if (!record) return true;
  return (
    record.termsVersion !== LEGAL_VERSION ||
    record.privacyVersion !== LEGAL_VERSION
  );
}

export function hasValidLegalConsent(): boolean {
  return !needsLegalReacceptance();
}
