/** Bump when Terms or Privacy change materially — prompts re-acceptance in the app. */
export const LEGAL_VERSION = "2026-05-23";

export const LEGAL_LAST_UPDATED = "May 23, 2026";

/** Replace with your legal entity name and contact before commercial launch. */
export const LEGAL_OPERATOR_NAME = "MIMS";
export const LEGAL_CONTACT_EMAIL = "support@mims.app";

export const APP_TAGLINE =
  "Educational pricing and deal-prep estimates for independent freelancers.";

export const LOADING_STEPS = [
  "Pulling freelance market rate estimates…",
  "Researching the client…",
  "Estimating budget capacity…",
  "Scoring close-likelihood…",
  "Preparing your deal guidance…",
] as const;

export const APP_DISCLAIMER =
  "MIMS provides educational pricing and deal-prep estimates based on the information you enter. Results are not legal, financial, tax, accounting, or contract advice, and are not a guarantee of what any client will accept. MIMS is for independent freelance professionals only. Review your own agreements, confirm freelance market fit, and use your judgment before sending any quote, invoice, or scope.";

export const DOC_EXPORT_DISCLAIMER =
  "DRAFT — NOT LEGAL ADVICE. This document was generated by MIMS as a starting template from your inputs. It is not a lawyer-drafted agreement. Have a qualified attorney review and customize all terms (including usage, payment, kill fees, and cancellation) before sending to a client or signing.";

export const CONSENT_STORAGE_KEY = "mimsLegalConsent";

export type LegalConsentRecord = {
  termsVersion: string;
  privacyVersion: string;
  acceptedAt: string;
};

export function recordLegalConsent(): void {
  if (typeof window === "undefined") return;
  const record: LegalConsentRecord = {
    termsVersion: LEGAL_VERSION,
    privacyVersion: LEGAL_VERSION,
    acceptedAt: new Date().toISOString(),
  };
  localStorage.setItem(CONSENT_STORAGE_KEY, JSON.stringify(record));
}

export function readLegalConsent(): LegalConsentRecord | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(CONSENT_STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as LegalConsentRecord;
  } catch {
    return null;
  }
}

/** True if user must accept (or re-accept) current Terms & Privacy. */
export function needsLegalReacceptance(): boolean {
  const record = readLegalConsent();
  if (!record) return true;
  return (
    record.termsVersion !== LEGAL_VERSION ||
    record.privacyVersion !== LEGAL_VERSION
  );
}

export function hasValidLegalConsent(): boolean {
  return !needsLegalReacceptance();
}
